import { isoDate } from "./money";
import type { LedgerState } from "./types";

export const SEED_IDS = {
  maya: "p-maya",
  jordan: "p-jordan",
  alex: "p-alex",
  priya: "p-priya",
  chase: "s-chase",
  amex: "s-amex",
  capitalOne: "s-capital-one",
  debit: "s-debit",
  electric: "s-electric",
  wifi: "s-wifi",
  rent: "s-rent",
} as const;

export function createSeed(): LedgerState {
  return {
    currentUserId: SEED_IDS.maya,
    people: [
      { id: SEED_IDS.maya, name: "Maya", color: "#2F6F5E" },
      { id: SEED_IDS.jordan, name: "Jordan", color: "#C45C26" },
      { id: SEED_IDS.alex, name: "Alex", color: "#3D5A80" },
      { id: SEED_IDS.priya, name: "Priya", color: "#7A5C8E" },
    ],
    sources: [
      {
        id: SEED_IDS.chase,
        name: "Maya's Chase Sapphire",
        kind: "card",
        ownerId: SEED_IDS.maya,
        last4: "4412",
      },
      {
        id: SEED_IDS.amex,
        name: "Jordan's Amex Gold",
        kind: "card",
        ownerId: SEED_IDS.jordan,
        last4: "1008",
      },
      {
        id: SEED_IDS.capitalOne,
        name: "Alex's Capital One",
        kind: "card",
        ownerId: SEED_IDS.alex,
        last4: "7731",
      },
      {
        id: SEED_IDS.debit,
        name: "Priya's Debit",
        kind: "card",
        ownerId: SEED_IDS.priya,
        last4: "2290",
      },
      {
        id: SEED_IDS.electric,
        name: "Electric",
        kind: "utility",
        provider: "ConEd",
      },
      {
        id: SEED_IDS.wifi,
        name: "Wi-Fi",
        kind: "utility",
        provider: "Spectrum",
      },
      {
        id: SEED_IDS.rent,
        name: "Rent portal",
        kind: "utility",
        provider: "Building app",
      },
    ],
    expenses: [
      {
        id: "e-dinner",
        title: "Friday dinner",
        amountCents: 12800,
        date: isoDate(-11),
        dueDate: isoDate(-4),
        paidById: SEED_IDS.maya,
        usedById: SEED_IDS.maya,
        sourceId: SEED_IDS.chase,
        notes: "Tacos and a pitcher. Maya's card was passed around the table.",
        createdAt: isoDate(-11),
        shares: [
          { personId: SEED_IDS.maya, amountCents: 3200, status: "paid", paidAt: isoDate(-11), repaidWith: "paid-the-card" },
          { personId: SEED_IDS.jordan, amountCents: 3200, status: "unpaid" },
          { personId: SEED_IDS.alex, amountCents: 3200, status: "paid", paidAt: isoDate(-6), repaidWith: "venmo" },
          { personId: SEED_IDS.priya, amountCents: 3200, status: "unpaid" },
        ],
      },
      {
        id: "e-electric",
        title: "August electric bill",
        amountCents: 18600,
        date: isoDate(-18),
        dueDate: isoDate(-11),
        paidById: SEED_IDS.jordan,
        usedById: SEED_IDS.jordan,
        sourceId: SEED_IDS.electric,
        chargedToSourceId: SEED_IDS.amex,
        notes: "ConEd autopay hit Jordan's Amex.",
        createdAt: isoDate(-18),
        shares: [
          { personId: SEED_IDS.jordan, amountCents: 4650, status: "paid", paidAt: isoDate(-18), repaidWith: "paid-the-card" },
          { personId: SEED_IDS.maya, amountCents: 4650, status: "paid", paidAt: isoDate(-14), repaidWith: "zelle" },
          { personId: SEED_IDS.alex, amountCents: 4650, status: "unpaid" },
          { personId: SEED_IDS.priya, amountCents: 4650, status: "paid", paidAt: isoDate(-12), repaidWith: "venmo" },
        ],
      },
      {
        id: "e-groceries",
        title: "Costco run",
        amountCents: 6450,
        date: isoDate(-5),
        dueDate: isoDate(2),
        paidById: SEED_IDS.maya,
        usedById: SEED_IDS.alex,
        sourceId: SEED_IDS.chase,
        notes: "Alex borrowed Maya's Chase at Costco.",
        createdAt: isoDate(-5),
        shares: [
          { personId: SEED_IDS.maya, amountCents: 2150, status: "paid", paidAt: isoDate(-5), repaidWith: "paid-the-card" },
          { personId: SEED_IDS.alex, amountCents: 2150, status: "unpaid" },
          { personId: SEED_IDS.jordan, amountCents: 2150, status: "unpaid" },
        ],
      },
      {
        id: "e-wifi",
        title: "Wi-Fi — Spectrum",
        amountCents: 7999,
        date: isoDate(-8),
        dueDate: isoDate(-1),
        paidById: SEED_IDS.maya,
        usedById: SEED_IDS.maya,
        sourceId: SEED_IDS.wifi,
        chargedToSourceId: SEED_IDS.chase,
        createdAt: isoDate(-8),
        shares: [
          { personId: SEED_IDS.maya, amountCents: 2000, status: "paid", paidAt: isoDate(-8), repaidWith: "paid-the-card" },
          { personId: SEED_IDS.jordan, amountCents: 2000, status: "unpaid" },
          { personId: SEED_IDS.alex, amountCents: 2000, status: "unpaid" },
          { personId: SEED_IDS.priya, amountCents: 1999, status: "paid", paidAt: isoDate(-3), repaidWith: "cash" },
        ],
      },
      {
        id: "e-uber",
        title: "Uber to the airport",
        amountCents: 4200,
        date: isoDate(-2),
        dueDate: isoDate(5),
        paidById: SEED_IDS.alex,
        usedById: SEED_IDS.jordan,
        sourceId: SEED_IDS.capitalOne,
        notes: "Jordan booked the ride on Alex's Capital One.",
        createdAt: isoDate(-2),
        shares: [
          { personId: SEED_IDS.alex, amountCents: 2100, status: "paid", paidAt: isoDate(-2), repaidWith: "paid-the-card" },
          { personId: SEED_IDS.jordan, amountCents: 2100, status: "unpaid" },
        ],
      },
      {
        id: "e-netflix",
        title: "Netflix",
        amountCents: 1599,
        date: isoDate(-20),
        dueDate: isoDate(-13),
        paidById: SEED_IDS.priya,
        usedById: SEED_IDS.priya,
        sourceId: SEED_IDS.debit,
        createdAt: isoDate(-20),
        shares: [
          { personId: SEED_IDS.priya, amountCents: 400, status: "paid", paidAt: isoDate(-20), repaidWith: "paid-the-card" },
          { personId: SEED_IDS.maya, amountCents: 400, status: "paid", paidAt: isoDate(-16), repaidWith: "venmo" },
          { personId: SEED_IDS.jordan, amountCents: 400, status: "paid", paidAt: isoDate(-15), repaidWith: "zelle" },
          { personId: SEED_IDS.alex, amountCents: 399, status: "paid", paidAt: isoDate(-14), repaidWith: "venmo" },
        ],
      },
    ],
  };
}
